### PR TITLE
Initial Jekyll site based on Holo Alfa theme

### PR DESCRIPTION
**Pull request by d2s**
Content migrated from the master branch in Markdown format.
HTML metadata migrated from the old gh-pages version.

Theme https://github.com/steinvc/holo-alfa is under MIT license.

### CODE REVIEW

**Comment by d2s** [comment]
Additional details from the [README.md](https://github.com/steinvc/holo-alfa/blob/master/README.md) of the theme:

-----

### Configuration ###

Edit `_config.yml`!

You can find `_config.yml` in your site's root directory. This configuration file contains some necessary settings and some optional customization settings. **All settings are explained in `_config.yml` itself.**

There are some customizations that can't be done in `_config.yml`. These include:

* Editing the About, Contact and Archive page.
* Adding or removing pages from the navigation. This can be done in `\_includes\navigation.html`.
* The "thanks" page after a message has been send through the contact page: `thanks.md`
* The gradient on cover images: `\_includes\gradient.css` (this is explained in `_config.yml`).

Also make sure to replace the placeholder favicons and the `\img\og-image.jpg` with your own.

### Start the Jekyll server ###

Run this command at the root of your site:

```
$ jekyll serve
```

> To run Jekyll in a way that matches the GitHub Pages build server, run Jekyll with Bundler. Use the command `bundle exec jekyll serve`.

When everything is OK, your site should now be available at `http://localhost:4000`.

That's it.

**Comment by d2s** [comment]
This pull request is related to issues #5 and #1 (at least).

**Comment by d2s** [comment]
Additional resources for learning to use [Jekyll](http://jekyllrb.com/) –based site structure.

- [Quick introduction](https://24ways.org/2013/get-started-with-github-pages/) to how GitHub Pages work.
(Related to #5 _gh-pages Jekyll-kytkentä_ issue.)

- If you want to run Ruby –based site on your local computer 
  (for example, when developing site layout forward),
  [install Ruby](http://guides.railsgirls.com/install/) to your own desktop.

**Comment by Mygee** [comment]
Uuden ulkoasun asentaminen

**Comment by pe3** [comment]
@d2s ja @Mygee pitäiskö sivuston nyt näyttää tältä? mulla näyttää
screen shot 2015-12-01 at 13 28 28

**Comment by apoikola** [comment]
@pe3 varmaan pitäisi näyttää ja näyttää tältä: http://avoinrajapinta.fi/

**Pull request merged**
